theme: minima
title: All About Rishi Mendiratta
author: Rishi Mendiratta
email: rishimendiratta8@gmail.com
description: The name, picture, socials, and brag sheet for Rishi Mendiratta
# social links

github_username:  rishimen

show_excerpts: true # set to false to remove excerpts on the homepage
